name: Create Chatwork Task

on:
  pull_request:
    types: [review_requested]
  workflow_dispatch:

jobs:
  create-chatwork-task:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Info
        run: |
          echo "Event Action: ${{ github.event.action }}"
          echo "Event Type: ${{ github.event_name }}"
          echo "Created At: ${{ github.event.pull_request.created_at }}"
          echo "Updated At: ${{ github.event.pull_request.updated_at }}"
          echo "Labels: ${{ toJSON(github.event.pull_request.labels) }}"
          echo "Requested Reviewer: ${{ github.event.requested_reviewer.login }}"
      - name: Create Chatwork Task
        env:
          CHATWORK_API_TOKEN: ${{ secrets.CHATWORK_API_TOKEN }}
          CHATWORK_ROOM_ID: ${{ secrets.CHATWORK_ROOM_ID }}
          CHATWORK_USER_MAPPING: ${{ secrets.CHATWORK_USER_MAPPING }}
        run: |
          # PRのレビュワー一覧を取得
          # 新しいレビュワー（今回追加された）を取得
          new_reviewer="${{ github.event.requested_reviewer.login }}"

          echo "New Reviewer: $new_reviewer"

          # 既存のレビュワー一覧を取得
          existing_reviewers=$(echo '${{ toJSON(github.event.pull_request.requested_reviewers) }}' | jq -r '.[].login' | tr '\n' ' ')

          echo "Existing Reviewers: $existing_reviewers"

          # github-username2でマッピングされているChatwork IDを取得
          github_username2_chatwork_id=$(echo $CHATWORK_USER_MAPPING | jq -r ".[\"github-username2\"]")

          echo "Github Username2 Chatwork ID: $github_username2_chatwork_id"

          # 両方を結合（重複を避けるため）
          github_reviewers="$new_reviewer $existing_reviewers"
          github_reviewers=$(echo "$github_reviewers" | tr ' ' '\n' | sort -u | tr '\n' ' ')

          # レビュワーのChatwork IDリストを作成
          reviewer_chatwork_ids=""
          for github_username in $github_reviewers; do
            if [ -n "$github_username" ]; then
              chatwork_account_id=$(echo $CHATWORK_USER_MAPPING | jq -r ".[\"$github_username\"]")
              if [ "$chatwork_account_id" != "null" ]; then
                reviewer_chatwork_ids="${reviewer_chatwork_ids}${chatwork_account_id},"
              fi
            fi
          done

          # 末尾のカンマを削除
          reviewer_chatwork_ids=${reviewer_chatwork_ids%,}

          # メッセージを作成
          message=$(cat << EOF
          ${{ github.event.pull_request.title }}

          レビューをお願いいたします(bow)
          URL：https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
          EOF
          )

          # 3営業日後の期限を計算
          function get_due_date() {
            current_date=$(date +%Y-%m-%d)
            count=0
            while [ $count -lt 3 ]; do
              current_date=$(date -d "$current_date +1 day" +%Y-%m-%d)
              day_of_week=$(date -d "$current_date" +%u)
              if [ "$day_of_week" -lt 6 ]; then # 月～金のみカウント
                ((count++))
              fi
            done
            echo $(date -d "$current_date" +%s)
          }

          # Chatworkにタスクを送信
          curl -X POST -H "X-ChatWorkToken: $CHATWORK_API_TOKEN" \
            -d "body=$message" \
            -d "to_ids=$reviewer_chatwork_ids" \
            -d "limit=$(get_due_date)" \
            "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM_ID/tasks"
